[pytest]
testpaths = tests

filterwarnings =
    ignore:.*BlockingPortal alias is deprecated.*:DeprecationWarning
    ignore:.*SwigPyPacked has no __module__ attribute.*:DeprecationWarning
    ignore:.*SwigPyObject has no __module__ attribute.*:DeprecationWarning
    ignore:.*swigvarlink has no __module__ attribute.*:DeprecationWarning